name = "deftime-for-todoist"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "deftime-for-todoist-dev"

[env.production]
name = "deftime-for-todoist"

[[d1_databases]]
binding = "DB"
database_name = "deftime-users"
database_id = "a8ba9cc4-0ba9-450b-9cea-6ea2ccf141f1"

[vars]
CLIENT_ID = "de8f833998b943e7a41cbb5018c44d2d"
REDIRECT_URI = "https://deftime.todoist.rosenpin.io/redirect"
